export const SCENARIOS = {
  toast: {
    contaCadastrada: { title: "Account created", description: "Account successfully registered" },
    beneficioFiscalAdicionado: { title: "Tax benefit added", description: "Tax benefit successfully added" },
    contatoAdicionado: { title: "Contact added", description: "Contact successfully added" },
    anexoEnviado: { title: "Attachment uploaded", description: "File successfully uploaded" },
    erroCpfCnpjJaCadastrado: { title: "Registration failed", description: "Tax ID already registered" },
    erroSalvarConta: { title: "Could not save account", description: "An error occurred while saving" },
    erroEnviarSap: { title: "ERP sync failed", description: "Could not send data to ERP" },
    erroAnexarArquivo: { title: "Upload failed", description: "Could not attach the file" },
  },
  alert: {
    contaAguardandoValidacao: { variant: "info" as const, title: "Pending validation", description: "Account is awaiting approval" },
    integracaoSapFalhou: { variant: "error" as const, title: "ERP integration failed", description: "Could not sync with ERP" },
    beneficioFiscalExpirado: { variant: "warning" as const, title: "Tax benefit expired", description: "This benefit is no longer valid" },
    contaRejeitadaSap: { variant: "error" as const, title: "Account rejected by ERP", description: "ERP returned a rejection for this account" },
  },
  tooltip: {
    clienteInternacional: { title: "International customer", description: "Tax ID becomes optional for international accounts" },
    tipoRelacao: { title: "Relationship type", description: "Automatically determined by the business activity code" },
    grupoEconomico: { title: "Economic group", description: "Linked accounts require credit department validation" },
    beneficioFiscal: { title: "Tax benefit", description: "Requires approval from Registration / Admin" },
    contatoPrincipal: { title: "Primary contact", description: "Only one primary contact is allowed per account" },
    multiplasIEs: { title: "Multiple state registrations", description: "Each registration must have a unique address" },
  },
  modal: {
    cancelarCadastro: { title: "Cancel registration", description: "Unsaved changes will be lost.", confirmLabel: "Yes, cancel", variant: "destructive" as const },
    removerContato: { title: "Remove contact", description: "Are you sure you want to remove this contact?", confirmLabel: "Yes, remove", variant: "destructive" as const },
    removerIE: { title: "Remove state registration", description: "Are you sure you want to remove this registration?", confirmLabel: "Yes, remove", variant: "destructive" as const },
    selecionarEnderecoNF: { title: "Select invoice address", description: "Choose the address to use on the invoice", confirmLabel: "Confirm", variant: "default" as const },
  },
  inlineError: {
    cpfCnpjInvalido: "Invalid tax ID",
    cpfCnpjDuplicado: "Tax ID already in use",
    cepInvalido: "Invalid postal code",
    paisNaoSelecionado: "Country not selected",
    grupoEconomicoSemMatriz: "Economic group has no parent company",
    grupoEconomicoNaoEncontrado: "Economic group not found",
    anexoObrigatorioFaltando: "Required attachment missing",
    contatoObrigatorioFaltando: "Required contact missing",
  },
} as const
